# auto: true
# url: https://github.com/rancher/turtles.git
# chartRepoBranch: charts/v0.23
# subdirectory: charts/rancher-turtles
# workingDir: charts

url: https://github.com/rancher/turtles/releases/download/v0.22.0/rancher-turtles-0.22.0.tgz
version: 109.0.0
doNotRelease: false
