# auto: true
# url: https://github.com/rancher/turtles.git
# chartRepoBranch: charts/v0.23
# subdirectory: charts/rancher-turtles
# workingDir: charts

url: https://github.com/rancher/turtles/releases/download/v0.20.0-rc.0/rancher-turtles-0.20.0-rc.0.tgz
version: 107.0.1
doNotRelease: false
