auto: true
url: https://github.com/furkatgofurov7/turtles.git
chartRepoBranch: release-0.23
subdirectory: charts/rancher-turtles
workingDir: rancher-turtles
additionalCharts:
  - workingDir: rancher-turtles-providers
    upstreamOptions:
      url: https://github.com/furkatgofurov7/turtles.git
      chartRepoBranch: release-0.23
      subdirectory: charts/rancher-turtles-providers